CREATE TABLE "announcement_reads" (
	"user" varchar(16) NOT NULL,
	"announcement" integer NOT NULL,
	"seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "announcement_reads_user_announcement_pk" PRIMARY KEY("user","announcement")
);
--> statement-breakpoint
CREATE TABLE "announcements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "balance_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "balance_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user" varchar(16) NOT NULL,
	"value" integer NOT NULL,
	"description" varchar(255) NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pending_notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pending_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user" varchar(16) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rsvps" (
	"hca_id" varchar(16) PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"slack_id" varchar(16) NOT NULL,
	"name" varchar(255) NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"ysws_eligible" boolean NOT NULL,
	"verification_status" varchar(16) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shop_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"album" varchar(255) NOT NULL,
	"artist" varchar(255) NOT NULL,
	"genre" varchar(255) NOT NULL,
	"image" text NOT NULL,
	"description" text NOT NULL,
	"media" varchar(45) NOT NULL,
	"urls" jsonb NOT NULL,
	"added" timestamp with time zone DEFAULT now() NOT NULL,
	"price" integer NOT NULL,
	"staff_pick_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shop_orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shop_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user" varchar(16) NOT NULL,
	"item" integer NOT NULL,
	"status" varchar(64) DEFAULT 'idle' NOT NULL,
	"message" text,
	"admin_message" text,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shop_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user" varchar(16) NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"album" varchar(255) NOT NULL,
	"artist" varchar(255) NOT NULL,
	"media" varchar(45) NOT NULL,
	"status" varchar(24) DEFAULT 'idle' NOT NULL,
	"message" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"hca_id" varchar(16) PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"slack_id" varchar(16) NOT NULL,
	"name" varchar(255) NOT NULL,
	"created" timestamp with time zone DEFAULT now() NOT NULL,
	"ysws_eligible" boolean NOT NULL,
	"verification_status" varchar(16) NOT NULL,
	CONSTRAINT "users_slack_id_unique" UNIQUE("slack_id")
);
--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_user_users_hca_id_fk" FOREIGN KEY ("user") REFERENCES "public"."users"("hca_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "announcement_reads" ADD CONSTRAINT "announcement_reads_announcement_announcements_id_fk" FOREIGN KEY ("announcement") REFERENCES "public"."announcements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "balance_events" ADD CONSTRAINT "balance_events_user_users_hca_id_fk" FOREIGN KEY ("user") REFERENCES "public"."users"("hca_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pending_notifications" ADD CONSTRAINT "pending_notifications_user_users_hca_id_fk" FOREIGN KEY ("user") REFERENCES "public"."users"("hca_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_orders" ADD CONSTRAINT "shop_orders_user_users_hca_id_fk" FOREIGN KEY ("user") REFERENCES "public"."users"("hca_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_orders" ADD CONSTRAINT "shop_orders_item_shop_items_id_fk" FOREIGN KEY ("item") REFERENCES "public"."shop_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_requests" ADD CONSTRAINT "shop_requests_user_users_hca_id_fk" FOREIGN KEY ("user") REFERENCES "public"."users"("hca_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fk_announcement_reads_announcements1_idx" ON "announcement_reads" USING btree ("announcement");--> statement-breakpoint
CREATE INDEX "fk_balance_events_users1_idx" ON "balance_events" USING btree ("user");--> statement-breakpoint
CREATE INDEX "fk_pending_notifications_users1_idx" ON "pending_notifications" USING btree ("user");--> statement-breakpoint
CREATE INDEX "fk_shop_orders_users1_idx" ON "shop_orders" USING btree ("user");--> statement-breakpoint
CREATE INDEX "fk_shop_orders_shop_items1_idx" ON "shop_orders" USING btree ("item");--> statement-breakpoint
CREATE INDEX "fk_shop_requests_users_idx" ON "shop_requests" USING btree ("user");